site_name: TechNova Partners – ML Deployment
site_description: Déploiement d’un modèle de Machine Learning avec FastAPI et PostgreSQL
site_author: Stéphane Gonzalez

theme:
  name: material
  language: fr
  palette:
    primary: teal
    accent: cyan

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]

nav:
  - Accueil: index.md
  - API:
      - app.api: api_reference/app_api.md
      - app.models: api_reference/app_models.md
      - domain.domain: api_reference/domain.md
      - technova_service: api_reference/technova_service.md
  - Base de données: init_base/database.md
  - Sécurité: securite/security.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
